const freezeLines = (lines) => Object.freeze(lines.map((line) => Object.freeze(line)));

export const ALGORITHMS = Object.freeze({
  bubble: Object.freeze({
    name: "Bubble Sort",
    shortName: "Bubble",
    description:
      "Compare neighbors and exchange any pair that is out of order. Each pass floats one large value into its final position.",
    invariant: "After every pass, the sorted suffix is final and never needs to move again.",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    accent: "#55e6c1",
    pseudocode: freezeLines([
      { id: "pass", code: "for each unsorted pass", depth: 0 },
      { id: "reset", code: "swapped ← false", depth: 1 },
      { id: "scan", code: "for each neighboring pair", depth: 1 },
      { id: "compare", code: "if left > right", depth: 2 },
      { id: "swap", code: "swap(left, right)", depth: 3 },
      { id: "settled", code: "mark pass end as sorted", depth: 1 },
      { id: "stop", code: "if not swapped: stop", depth: 1 },
    ]),
  }),
  selection: Object.freeze({
    name: "Selection Sort",
    shortName: "Selection",
    description:
      "Scan the unsorted region for its smallest value, then place that value at the next open position.",
    invariant: "The sorted prefix always contains the smallest values seen so far, in final order.",
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: false,
    inPlace: true,
    accent: "#ffd166",
    pseudocode: freezeLines([
      { id: "position", code: "for each open position", depth: 0 },
      { id: "minimum", code: "minimum ← open position", depth: 1 },
      { id: "scan", code: "for each remaining value", depth: 1 },
      { id: "compare", code: "if value < minimum", depth: 2 },
      { id: "update", code: "minimum ← value", depth: 3 },
      { id: "swap", code: "swap(open, minimum)", depth: 1 },
      { id: "settled", code: "mark open position sorted", depth: 1 },
    ]),
  }),
  insertion: Object.freeze({
    name: "Insertion Sort",
    shortName: "Insertion",
    description:
      "Take the next value and walk it left through the sorted prefix until it reaches the first valid opening.",
    invariant: "Before the next value is picked up, every value to its left is already sorted.",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    accent: "#ff7a8a",
    pseudocode: freezeLines([
      { id: "key", code: "key ← next value", depth: 0 },
      { id: "scan", code: "scan sorted values to the left", depth: 1 },
      { id: "compare", code: "while left > key", depth: 1 },
      { id: "shift", code: "shift left value right", depth: 2 },
      { id: "insert", code: "insert key into the opening", depth: 1 },
    ]),
  }),
  merge: Object.freeze({
    name: "Merge Sort",
    shortName: "Merge",
    description:
      "Divide the array into smaller ranges, sort those ranges, then weave them together from smallest to largest.",
    invariant: "Every completed merge replaces two sorted halves with one larger sorted range.",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    space: "O(n)",
    stable: true,
    inPlace: false,
    accent: "#8ea1ff",
    pseudocode: freezeLines([
      { id: "split", code: "split range at its midpoint", depth: 0 },
      { id: "left", code: "mergeSort(left half)", depth: 1 },
      { id: "right", code: "mergeSort(right half)", depth: 1 },
      { id: "begin", code: "merge the two sorted halves", depth: 1 },
      { id: "compare", code: "compare the front values", depth: 2 },
      { id: "take", code: "write the smaller value next", depth: 2 },
      { id: "remainder", code: "copy any values left over", depth: 2 },
      { id: "merged", code: "mark the range merged", depth: 1 },
    ]),
  }),
  quick: Object.freeze({
    name: "Quick Sort",
    shortName: "Quick",
    description:
      "Choose a pivot, partition smaller values to its left and larger values to its right, then repeat inside each partition.",
    invariant: "Every finished partition locks its pivot into the position it will occupy in the final array.",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n²)",
    space: "O(log n)",
    stable: false,
    inPlace: true,
    accent: "#a78bfa",
    pseudocode: freezeLines([
      { id: "partition", code: "partition the current range", depth: 0 },
      { id: "pivot", code: "pivot ← last value", depth: 1 },
      { id: "scan", code: "scan values before the pivot", depth: 1 },
      { id: "compare", code: "if value ≤ pivot", depth: 2 },
      { id: "swap", code: "move value into left partition", depth: 3 },
      { id: "place", code: "place pivot between partitions", depth: 1 },
      { id: "left", code: "quickSort(left partition)", depth: 1 },
      { id: "right", code: "quickSort(right partition)", depth: 1 },
    ]),
  }),
  heap: Object.freeze({
    name: "Heap Sort",
    shortName: "Heap",
    description:
      "Build a max heap, repeatedly move its largest value to the end, and repair the remaining heap after every extraction.",
    invariant: "The heap root is the largest unsettled value, while the suffix beyond the heap is already final.",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    space: "O(1)",
    stable: false,
    inPlace: true,
    accent: "#ff9f43",
    pseudocode: freezeLines([
      { id: "build", code: "build a max heap", depth: 0 },
      { id: "sift", code: "sift the root downward", depth: 1 },
      { id: "compare", code: "find the larger child", depth: 2 },
      { id: "swap", code: "swap parent with larger child", depth: 2 },
      { id: "extract", code: "swap heap maximum to the end", depth: 0 },
      { id: "lock", code: "shrink heap; lock that position", depth: 1 },
    ]),
  }),
  shell: Object.freeze({
    name: "Shell Sort",
    shortName: "Shell",
    description:
      "Run insertion-style passes across wide gaps, then shrink the gap until the final pass compares ordinary neighbors.",
    invariant: "After each gap pass, values in every gap-separated subsequence are ordered relative to one another.",
    best: "O(n log n)",
    average: "≈ O(n^1.5)",
    worst: "O(n²)",
    space: "O(1)",
    stable: false,
    inPlace: true,
    accent: "#f472b6",
    pseudocode: freezeLines([
      { id: "gap", code: "gap ← floor(length / 2)", depth: 0 },
      { id: "key", code: "pick the next value in this gap", depth: 1 },
      { id: "compare", code: "while gap-left > key", depth: 1 },
      { id: "shift", code: "shift gap-left value right", depth: 2 },
      { id: "insert", code: "insert key into its gap opening", depth: 1 },
      { id: "next", code: "gap ← floor(gap / 2)", depth: 0 },
    ]),
  }),
  counting: Object.freeze({
    name: "Counting Sort",
    shortName: "Counting",
    description:
      "Count each integer value, accumulate those counts into output positions, then place values without comparing pairs.",
    invariant: "Accumulated counts identify the final output interval owned by every distinct integer value.",
    best: "O(n + k)",
    average: "O(n + k)",
    worst: "O(n + k)",
    space: "O(n + k)",
    stable: true,
    inPlace: false,
    accent: "#4dd4ff",
    pseudocode: freezeLines([
      { id: "init", code: "create one counter per value", depth: 0 },
      { id: "count", code: "count every input value", depth: 0 },
      { id: "prefix", code: "accumulate counter totals", depth: 0 },
      { id: "output", code: "place inputs right-to-left", depth: 0 },
      { id: "copy", code: "copy ordered output back", depth: 0 },
    ]),
  }),
  radix: Object.freeze({
    name: "Radix Sort",
    shortName: "Radix",
    description:
      "Group integers by one decimal digit at a time, preserving bucket order from the ones place toward the most significant digit.",
    invariant: "After a digit pass, the array is stably ordered by every digit processed so far.",
    best: "O(d(n + 10))",
    average: "O(d(n + 10))",
    worst: "O(d(n + 10))",
    space: "O(n + 10)",
    stable: true,
    inPlace: false,
    accent: "#c084fc",
    pseudocode: freezeLines([
      { id: "normalize", code: "offset keys so the minimum is zero", depth: 0 },
      { id: "digit", code: "for each decimal digit", depth: 0 },
      { id: "bucket", code: "append values to digit buckets", depth: 1 },
      { id: "collect", code: "collect buckets in order", depth: 1 },
      { id: "repeat", code: "move to the next digit", depth: 0 },
    ]),
  }),
  cocktail: Object.freeze({
    name: "Cocktail Shaker Sort",
    shortName: "Cocktail",
    description:
      "Sweep forward to move a large value right, then sweep backward to move a small value left, shrinking both boundaries.",
    invariant: "Each round locks one value at the right boundary and one value at the left boundary.",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    accent: "#fb7185",
    pseudocode: freezeLines([
      { id: "forward", code: "sweep left → right", depth: 0 },
      { id: "compare", code: "compare neighboring values", depth: 1 },
      { id: "swap", code: "swap if they are out of order", depth: 2 },
      { id: "right", code: "lock the right boundary", depth: 0 },
      { id: "backward", code: "sweep right → left", depth: 0 },
      { id: "left", code: "lock the left boundary", depth: 0 },
      { id: "stop", code: "stop if neither sweep swaps", depth: 0 },
    ]),
  }),
  "quick-three": Object.freeze({
    name: "Three-Way Quick Sort",
    shortName: "3-Way Quick",
    description:
      "Partition values into smaller, equal, and greater regions so duplicate pivot values finish together in one pass.",
    invariant: "Left values are smaller, middle values equal the pivot, and right values are larger.",
    best: "O(n)",
    average: "O(n log n)",
    worst: "O(n²)",
    space: "O(log n)",
    stable: false,
    inPlace: true,
    accent: "#22d3ee",
    pseudocode: freezeLines([
      { id: "pivot", code: "pivot ← first value", depth: 0 },
      { id: "compare", code: "classify value against pivot", depth: 0 },
      { id: "less", code: "if smaller: grow left region", depth: 1 },
      { id: "greater", code: "if greater: grow right region", depth: 1 },
      { id: "equal", code: "if equal: advance scan", depth: 1 },
      { id: "recurse", code: "sort only the two outer regions", depth: 0 },
    ]),
  }),
  introsort: Object.freeze({
    name: "IntroSort",
    shortName: "IntroSort",
    description:
      "Lead with Quick Sort, switch to Heap Sort at a recursion limit, and finish small ranges with Insertion Sort.",
    invariant: "Each range uses the fastest safe strategy while the depth limit protects the O(n log n) worst case.",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    space: "O(log n)",
    stable: false,
    inPlace: true,
    accent: "#f59e0b",
    pseudocode: freezeLines([
      { id: "limit", code: "limit ← 2 × floor(log₂ n)", depth: 0 },
      { id: "partition", code: "quick-partition while depth remains", depth: 0 },
      { id: "compare", code: "classify value against pivot", depth: 1 },
      { id: "fallback", code: "at limit: heap-sort range", depth: 0 },
      { id: "insertion", code: "for short range: insertion-sort", depth: 0 },
      { id: "recurse", code: "continue on outer partitions", depth: 0 },
    ]),
  }),
  timsort: Object.freeze({
    name: "TimSort",
    shortName: "TimSort",
    description:
      "Discover existing ordered runs, extend short ones with binary insertion, and merge a balanced stack of runs.",
    invariant: "Every stacked run is sorted, while stack rules keep later merges balanced.",
    best: "O(n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    space: "O(n)",
    stable: true,
    inPlace: false,
    accent: "#34d399",
    note: "Teaching implementation models natural runs and stack invariants without galloping mode.",
    pseudocode: freezeLines([
      { id: "runs", code: "discover an ascending or descending run", depth: 0 },
      { id: "reverse", code: "reverse a strictly descending run", depth: 1 },
      { id: "extend", code: "extend short run by binary insertion", depth: 0 },
      { id: "push", code: "push run onto the run stack", depth: 0 },
      { id: "merge", code: "merge runs to preserve stack rules", depth: 0 },
    ]),
  }),
  bucket: Object.freeze({
    name: "Bucket Sort",
    shortName: "Bucket",
    description:
      "Distribute nearby values into ordered ranges, sort each small bucket, then collect buckets from low to high.",
    invariant: "Every value in an earlier bucket is no greater than every value in a later bucket.",
    best: "O(n + k)",
    average: "O(n + k)",
    worst: "O(n²)",
    space: "O(n + k)",
    stable: true,
    inPlace: false,
    accent: "#38bdf8",
    pseudocode: freezeLines([
      { id: "create", code: "create ordered value-range buckets", depth: 0 },
      { id: "distribute", code: "append each value to its bucket", depth: 0 },
      { id: "sort", code: "stable-sort each small bucket", depth: 0 },
      { id: "collect", code: "collect buckets from low to high", depth: 0 },
    ]),
  }),
  bitonic: Object.freeze({
    name: "Bitonic Sort Network",
    shortName: "Bitonic",
    description:
      "Build opposite-direction subsequences and merge them through a fixed compare-exchange network suited to parallel hardware.",
    invariant: "Each stage orders a sequence through comparator pairs fixed by lane positions.",
    best: "O(n log² n)",
    average: "O(n log² n)",
    worst: "O(n log² n)",
    space: "O(log n)",
    stable: false,
    inPlace: true,
    accent: "#a78bfa",
    pseudocode: freezeLines([
      { id: "build", code: "build rising and falling subsequences", depth: 0 },
      { id: "merge", code: "merge a bitonic sequence", depth: 0 },
      { id: "compare", code: "compare fixed-distance lane pairs", depth: 1 },
      { id: "swap", code: "exchange pair if direction requires", depth: 2 },
    ]),
  }),
});
